name: Build PDF

on:
  pull_request:
    branches:
      - 'main'
    types:
      - closed
  
permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: tcc.tex
          extra_fonts: |
            ./fontes/*.ttf
          latexmk_use_xelatex: true

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: tcc.pdf

  generate_changelog:
    runs-on: ubuntu-latest
    needs: build_latex
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      
      - name: Install github_changelog_generator
        run: gem install github_changelog_generator

      - name: Generate Changelog
        run: |
          git fetch --tags --force
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          github_changelog_generator -u henriquesebastiao -p tcc --since-tag $latest_tag
        env:
          CHANGELOG_GITHUB_TOKEN: ${{ secrets.CHANGELOG_GITHUB_TOKEN }}
      
      - name: Upload CHANGELOG file
        uses: actions/upload-artifact@v4
        with:
          name: CHANGELOG
          path: CHANGELOG.md

  create_release:
    needs: generate_changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download PDF artifact
        uses: actions/download-artifact@v4
        with:
          name: PDF
          path: .
      
      - name: Download CHANGELOG artifact
        uses: actions/download-artifact@v4
        with:
          name: CHANGELOG
          path: .

      - name: Set date and commit hash
        id: set_vars
        run: |
          echo "DATE=$(date +'%Y-%m-%d')" >> "$GITHUB_ENV"
          echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.DATE }}-${{ env.COMMIT_HASH }}
          release_name: ${{ env.DATE }}-${{ env.COMMIT_HASH }}
          body_path: ./CHANGELOG.md
          draft: false
          prerelease: false

      - name: Upload PDF to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./tcc.pdf
          asset_name: tcc.pdf
          asset_content_type: application/pdf