name: Build LaTeX document

on:
  workflow_run:
    workflows: ["Lint"]
    types: [completed]
    branches:
      - 'main'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: tcc.tex
          extra_fonts: |
            ./fontes/*.ttf
          latexmk_use_xelatex: true

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: tcc.pdf
        
      - name: Set up Git configuration
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
  
      - name: Deploy PDF to GitHub Pages
        run: |
          mkdir gh-pages
          mv tcc.pdf gh-pages/
          cd gh-pages
          git init
          git add .
          git commit -m "build: Deploy do PDF via GitHub Pages"
          git branch -M main
          git remote add origin https://github.com/${{ github.repository }}.git
          git push -f origin main:gh-pages
  
      - name: Clean up
        run: |
          rm -rf gh-pages
            